In [1]:
import pandas as pd   
import numpy as np
from pandas import Series
from pandas import DataFrame as df

In [6]:
dict = {
    'Year' : [2015,2016,2017,2018,2019],
    'Population' : [30,32.2,34.5,35,36.3],
    'GDP' : [110,114,113,112,110]
}
df1 = pd.DataFrame(dict)
df1

Year  Population  GDP
0  2015        30.0  110
1  2016        32.2  114
2  2017        34.5  113
3  2018        35.0  112
4  2019        36.3  110

In [7]:
df1.head(3) # head

Year  Population  GDP
0  2015        30.0  110
1  2016        32.2  114
2  2017        34.5  113

In [8]:
df1.shape

(5, 3)

In [11]:
df1 = df(dict,columns=['Year', 'GDP', 'GDP per capita', 'Population'], index=[1,2,3,4,5])
df1

Year  GDP GDP per capita  Population
1  2015  110            NaN        30.0
2  2016  114            NaN        32.2
3  2017  113            NaN        34.5
4  2018  112            NaN        35.0
5  2019  110            NaN        36.3

In [15]:
df1['GDP per capita'] = [1.5,1.8,1.9,2.5,3.3]
df1

Year  GDP  GDP per capita  Population
1  2015  110             1.5        30.0
2  2016  114             1.8        32.2
3  2017  113             1.9        34.5
4  2018  112             2.5        35.0
5  2019  110             3.3        36.3

In [36]:
df1['111+'] = df1.GDP > 111
df1

Year  GDP  GDP per capita  Population   100+   111+
1  2015  110             1.5        30.0  False  False
2  2016  114             1.8        32.2   True   True
3  2017  113             1.9        34.5   True   True
4  2018  112             2.5        35.0   True   True
5  2019  110             3.3        36.3  False  False

In [37]:
del df1['111+']
del df1['100+']
df1

Year  GDP  GDP per capita  Population
1  2015  110             1.5        30.0
2  2016  114             1.8        32.2
3  2017  113             1.9        34.5
4  2018  112             2.5        35.0
5  2019  110             3.3        36.3

In [40]:
val = pd.Series([1750, 1560, 1270], index=[5, 3, 1])
df1['YAIM'] = val
df1

Year  GDP  GDP per capita  Population    YAIM
1  2015  110             1.5        30.0  1270.0
2  2016  114             1.8        32.2     NaN
3  2017  113             1.9        34.5  1560.0
4  2018  112             2.5        35.0     NaN
5  2019  110             3.3        36.3  1750.0

In [45]:
YAIM = [1700, 1670, 1600, 1590, 1400]
df1['YAIM'] = YAIM
df1

Year  GDP  GDP per capita  Population  YAIM
1  2015  110             1.5        30.0  1700
2  2016  114             1.8        32.2  1670
3  2017  113             1.9        34.5  1600
4  2018  112             2.5        35.0  1590
5  2019  110             3.3        36.3  1400

In [46]:
data = {
    'Uzbekistan':{2021:33.9, 2020:33.5, 2019:32.9, 2018:32.5, 2017:31.9},
    'Kazakhstan':{2021:18.9, 2020:18.7, 2019:18.5, 2018:18.3, 2017:18.1, 2016:17.8}
}
df2 = df(data)
df2

Uzbekistan  Kazakhstan
2016         NaN        17.8
2017        31.9        18.1
2018        32.5        18.3
2019        32.9        18.5
2020        33.5        18.7
2021        33.9        18.9

In [48]:
df2.T

2016  2017  2018  2019  2020  2021
Uzbekistan   NaN  31.9  32.5  32.9  33.5  33.9
Kazakhstan  17.8  18.1  18.3  18.5  18.7  18.9

In [54]:
df2.index.name = 'Yil'
df2 = df2.T
df2

Yil         2016  2017  2018  2019  2020  2021
Uzbekistan   NaN  31.9  32.5  32.9  33.5  33.9
Kazakhstan  17.8  18.1  18.3  18.5  18.7  18.9

In [60]:
arr = df2.values
arr

array([[ nan, 31.9, 32.5, 32.9, 33.5, 33.9],
       [17.8, 18.1, 18.3, 18.5, 18.7, 18.9]])

In [62]:
arr[0,0] = 0
arr

array([[ 0. , 31.9, 32.5, 32.9, 33.5, 33.9],
       [17.8, 18.1, 18.3, 18.5, 18.7, 18.9]])

**Working with Indexs**

In [2]:
data = {
    'Uzbekistan':{2021:33.9, 2020:33.5, 2019:32.9, 2018:32.5, 2017:31.9},
    'Kazakhstan':{2021:18.9, 2020:18.7, 2019:18.5, 2018:18.3, 2017:18.1, 2016:17.8}
}
df3 = df(data)
df3

Uzbekistan  Kazakhstan
2016         NaN        17.8
2017        31.9        18.1
2018        32.5        18.3
2019        32.9        18.5
2020        33.5        18.7
2021        33.9        18.9

In [4]:
cols = df3.columns
cols

Index(['Uzbekistan', 'Kazakhstan'], dtype='object')

In [6]:
indexs = df3.index
indexs

Int64Index([2016, 2017, 2018, 2019, 2020, 2021], dtype='int64')

In [7]:
'Tajikistan' in df3.columns

False

In [8]:
2017 in df3.index

True

In [9]:
print(df3.columns[0:1])

Index(['Uzbekistan'], dtype='object')


In [10]:
# We cannot change index
df3.index[0] = 2014 # cannot be changed

TypeError: Index does not support mutable operations

In [23]:
usernames = {"anvar":"anvarbek223", "olim":"olimtoy", "maryam":"mary334455","javohir":"javohir445"}
emails = {"anvar":"anvar@gmail.com", "olim":"olim@mail.ru", "maryam":"mary33@gmail.com","javohir":"javohir445@gmail.com"}

data = {
    'username':usernames,
    'email':emails
}
df4 = df(data)
df4

username                 email
anvar    anvarbek223       anvar@gmail.com
javohir   javohir445  javohir445@gmail.com
maryam    mary334455      mary33@gmail.com
olim         olimtoy          olim@mail.ru

In [4]:
df4.index

Index(['anvar', 'javohir', 'maryam', 'olim'], dtype='object')

In [5]:
arr = ['javohir', 'elbek', 'asilbek']
arr

['javohir', 'elbek', 'asilbek']

In [12]:
data2 = {
    'username' : {'maryam': 'maryamxon123', 'olim':'olim2005'},
    'email' : {'maryam': 'maryamxon123@outlook.com', 'olim': 'olimbek@gmail.com'}
    }
df5 = df(data2)
df5

username                     email
maryam  maryamxon123  maryamxon123@outlook.com
olim        olim2005         olimbek@gmail.com

In [24]:
df4 = df4.append(df5)
df4

username                     email
anvar     anvarbek223           anvar@gmail.com
javohir    javohir445      javohir445@gmail.com
maryam     mary334455          mary33@gmail.com
olim          olimtoy              olim@mail.ru
maryam   maryamxon123  maryamxon123@outlook.com
olim         olim2005         olimbek@gmail.com

In [25]:
newind = pd.Index(['olim', 'nafisa', 'hamida'])
newind

Index(['olim', 'nafisa', 'hamida'], dtype='object')

In [28]:
newind.isin(df4.index)

array([ True, False, False])

In [29]:
df4.index.difference(newind)

Index(['anvar', 'javohir', 'maryam'], dtype='object')

In [30]:
newind.difference(df4.index)

Index(['hamida', 'nafisa'], dtype='object')

In [37]:
newind.union(df4.index)

Index(['anvar', 'hamida', 'javohir', 'maryam', 'maryam', 'nafisa', 'olim'], dtype='object')

In [38]:
df4.index.delete(0)

Index(['javohir', 'maryam', 'olim', 'maryam', 'olim'], dtype='object')

In [39]:
newind.drop('olim')

Index(['nafisa', 'hamida'], dtype='object')

In [40]:
df4.index.insert(4,'ibrohim') # index 4 

Index(['anvar', 'javohir', 'maryam', 'olim', 'ibrohim', 'maryam', 'olim'], dtype='object')

In [41]:
df4.index.is_monotonic

False

In [42]:
df4.index.is_unique

False

In [43]:
newind.is_unique

True

In [44]:
df4.index.unique()

Index(['anvar', 'javohir', 'maryam', 'olim'], dtype='object')

In [46]:
data = {
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego'],
    'Population (millions)': [8.4, 3.9, 2.7, 2.3, 1.7, 1.6, 1.5, 1.4],
    'Average Temperature (Celsius)': [12, 21, 11, 23, 25, 14, 24, 19]
}

df6 = df(data)
df6

City  Population (millions)  Average Temperature (Celsius)
0      New York                    8.4                             12
1   Los Angeles                    3.9                             21
2       Chicago                    2.7                             11
3       Houston                    2.3                             23
4       Phoenix                    1.7                             25
5  Philadelphia                    1.6                             14
6   San Antonio                    1.5                             24
7     San Diego                    1.4                             19

In [48]:
df6.index = [1,2,3,4,5,6,7,8]
df6

City  Population (millions)  Average Temperature (Celsius)
1      New York                    8.4                             12
2   Los Angeles                    3.9                             21
3       Chicago                    2.7                             11
4       Houston                    2.3                             23
5       Phoenix                    1.7                             25
6  Philadelphia                    1.6                             14
7   San Antonio                    1.5                             24
8     San Diego                    1.4                             19

In [54]:
df6.reindex([8,7,6,5,4,3,2,1])
df6

City  Population (millions)  Average Temperature (Celsius)
1      New York                    8.4                             12
2   Los Angeles                    3.9                             21
3       Chicago                    2.7                             11
4       Houston                    2.3                             23
5       Phoenix                    1.7                             25
6  Philadelphia                    1.6                             14
7   San Antonio                    1.5                             24
8     San Diego                    1.4                             19

In [56]:
df6.reindex([3,4,5])

City  Population (millions)  Average Temperature (Celsius)
3  Chicago                    2.7                             11
4  Houston                    2.3                             23
5  Phoenix                    1.7                             25

In [62]:
df6.reindex(index=range(1,20), method='nearest') # nearest

City  Population (millions)  Average Temperature (Celsius)
1       New York                    8.4                             12
2    Los Angeles                    3.9                             21
3        Chicago                    2.7                             11
4        Houston                    2.3                             23
5        Phoenix                    1.7                             25
6   Philadelphia                    1.6                             14
7    San Antonio                    1.5                             24
8      San Diego                    1.4                             19
9      San Diego                    1.4                             19
10     San Diego                    1.4                             19
11     San Diego                    1.4                             19
12     San Diego                    1.4                             19
13     San Diego                    1.4                             19
14     San Diego                    1.4                             19
15     San Diego                    1.4                             19
16     San Diego                    1.4                             19
17     San Diego                    1.4                             19
18     San Diego                    1.4                             19
19     San Diego                    1.4                             19

In [64]:
df6.reindex(index=[8,7,6,5,4,3,2,1])

City  Population (millions)  Average Temperature (Celsius)
8     San Diego                    1.4                             19
7   San Antonio                    1.5                             24
6  Philadelphia                    1.6                             14
5       Phoenix                    1.7                             25
4       Houston                    2.3                             23
3       Chicago                    2.7                             11
2   Los Angeles                    3.9                             21
1      New York                    8.4                             12

In [67]:
df6.sample(2) # random 

City  Population (millions)  Average Temperature (Celsius)
8  San Diego                    1.4                             19
3    Chicago                    2.7                             11

In [69]:
df6.loc[[1,5,8],['City','Population (millions)']]

City  Population (millions)
1   New York                    8.4
5    Phoenix                    1.7
8  San Diego                    1.4