In [1]:
import numpy as np

#difference between np.array and python lists 
#adding
l = [1,2,3,4]
a = np.array([1,2,3,4])

l += [4]
print(l)

a += np.array([4])
print(a)

[1, 2, 3, 4, 4]
[5 6 7 8]


In [10]:
#multiplication
l = [1,2,3,4]
a = np.array([1,2,3,4])

l = l * 2
print(l)
a = a * 2
print(a)

[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


In [14]:
#Numpy some methods
a = np.array([1,2,3])
a[0] = 10
b = a * np.array([2,0,2])
print(b)

print(a)
print(a.shape) 
print(a.dtype) # data type of array
print(a.ndim) #dimension
print(a.size)
print(a.itemsize) #size in bytes





[20  0  6]
[10  2  3]
(3,)
int32
1
3
4


In [17]:
#Dot product
l1 = [1,2,3]
l2 = [4,5,6]
a1 = np.array(l1)
a2 = np.array(l2)

#dot in lists
dot = 0
for i in range(len(l1)):
    dot += l1[i] * l2[i]
print(dot)

#dot in numpy
dot = np.dot(a1,a2)
print(dot)

sum1 = a1 * a2
dot = np.sum(sum1)
print(dot)

#best way

dot = a1 @ a2
print(dot)


32
32
32
32
