In [2]:
import numpy as np

a = np.array([[1,2], [3,4]])

#print(a)
#print(a.shape)
#print(a[0,2]) # which = [0][2]
c = np.diag(a)

print(a.T)
print(np.linalg.inv(a)) #inverse
print(np.linalg.det(a)) #determinent

print(np.diag(c))


 

[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
[[1 0]
 [0 4]]


In [6]:
# Indexing and Slicing
a  = np.array([[1,2,3,4],[5,6,7,8]])
print(a[1,:])
print(a[0,1:3])

#Colums
print(a[:,1])

# Negative
print(a[-1,-2])


[5 6 7 8]
[2 3]
[2 6]
7


In [16]:
# Boolen
b = np.array([[1,2], [3,4], [5,6]])

bool_idx = b > 2
print(bool_idx)
print(b[b > 3])

c = np.where(b>2 , b ,0)
print(c)

[[False False]
 [ True  True]
 [ True  True]]
[4 5 6]
[[0 0]
 [3 4]
 [5 6]]


In [19]:
# Fancy Indexing
a = np.array([10,19,30,41,50,61])
print(a)
b = [1,3,5]
print(a[b])

even = np.argwhere(a%2==0).flatten()
print(a[even])

[10 19 30 41 50 61]
[19 41 61]
[10 30 50]
