In [1]:
import numpy as np

**Universal** **functions**

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#Exponention
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [3]:
# Square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [8]:
# Log e
np.log(arr[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [4]:
# Square
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
# Modf divides two parts reminder and natural number
arr1 = np.random.randn(10)
arr1

array([-1.45973137,  0.02653429, -0.119298  ,  0.40515151, -0.87743201,
       -0.44741022,  0.90321212, -1.11601713, -1.09759327, -0.5218143 ])

In [10]:
reminder, number = np.modf(arr1)
print(reminder)
print(number)

[-0.45973137  0.02653429 -0.119298    0.40515151 -0.87743201 -0.44741022
  0.90321212 -0.11601713 -0.09759327 -0.5218143 ]
[-1.  0. -0.  0. -0. -0.  0. -1. -1. -0.]


In [11]:
# Sign return 1 if number is n>0 and -1 if n<0
np.sign(arr1)

array([-1.,  1., -1.,  1., -1., -1.,  1., -1., -1., -1.])

In [12]:
# isnan return True if values is Nan
arr1[0] = np.NAN
arr1

array([        nan,  0.02653429, -0.119298  ,  0.40515151, -0.87743201,
       -0.44741022,  0.90321212, -1.11601713, -1.09759327, -0.5218143 ])

In [13]:
np.isnan(arr1)

array([ True, False, False, False, False, False, False, False, False,
       False])

**Where**

In [14]:
arr_a = np.array([1.1,1.2,1.3,1.4])
arr_b = np.array([2.1,2.2,2.3,2.4])
cond = np.array([True,True,False,True])
result = np.where(cond,arr_a,arr_b) # if cond is True get from arr_a if False get from arr_b
result

array([1.1, 1.2, 2.3, 1.4])

In [23]:
arr_c = np.random.randint(-10,10, size=(3,3))
result1 = np.where(arr_c>0,1,-1) # if number is n>0 return 1 otherwise -1
result1

array([[ 1, -1, -1],
       [ 1, -1,  1],
       [-1,  1,  1]])

**Statistics**

In [31]:
arr_d = np.random.randint(-100,100, size=(3,3))
arr_d

array([[ 28,  85,  38],
       [ 50, -62, -62],
       [ 39, -13,   6]])

In [32]:
arr_d.sum() # np.sum(arr_d) is okay too

109

In [34]:
print(arr_d.sum(axis=1)) # row-sum
print(arr_d.sum(axis=0)) # column-sum

[151 -74  32]
[117  10 -18]


In [35]:
arr_d.mean() # np.mean(arr_d) is okay too

12.11111111111111

In [36]:
print(arr_d.mean(axis=1)) # row-mean
print(arr_d.mean(axis=0)) # column-mean

[ 50.33333333 -24.66666667  10.66666667]
[39.          3.33333333 -6.        ]


In [38]:
#cumsum
arr_d.cumsum()
# summation steps

array([ 28, 113, 151, 201, 139,  77, 116, 103, 109])