Numpy Library



In [2]:
import numpy as np

In [ ]:
my_list = list(range(100000)) # Normal list
my_array = np.array(range(10000)) # Numpy array

In [ ]:
%time for _ in range(10): [x*2 for x in my_list] # Time for normal list

CPU times: user 68.7 ms, sys: 2.9 ms, total: 71.6 ms
Wall time: 71.4 ms


In [ ]:
%time for _ in range(10): my_array*2 # Vectorization

CPU times: user 1.28 ms, sys: 0 ns, total: 1.28 ms
Wall time: 1.17 ms


**Array Function**


In [ ]:
data1 = [[1,2,5,3], [12,7,8,3],[1,2.3,55,23]]
arr1 = np.array(data1)

In [ ]:
arr1

array([[ 1. ,  2. ,  5. ,  3. ],
       [12. ,  7. ,  8. ,  3. ],
       [ 1. ,  2.3, 55. , 23. ]])

In [ ]:
arr1.ndim # help to find 'size' of array

2

**Shape** **Function**

In [ ]:
arr1.shape # return result as a tuple

(3, 4)

In [ ]:
arr1.size # all elements size

12

In [ ]:
# 3 is a rows
# 4 is a columns that we have
arr1.shape[1]

4

**Zeros and Ones Function**

In [ ]:
arr2 = np.zeros((3,4)) # generate matrix with zeros with the shape of (3,4)
print(arr2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
arr3 = np.ones((3,4))
print(arr3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**Arange Function**

In [ ]:
arr4 = np.arange(4, 30 , 3) # this mean generate array numbers from 4 to 30 with difference 3
print(arr4)

[ 4  7 10 13 16 19 22 25 28]


In [ ]:
arr5 = np.arange(30) # automatically starts from 0
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [ ]:
rshape = np.arange(0,9,1).reshape(3,3) # reshapes the deminsion
rshape[2, :2]

array([6, 7])

**Random, Randint Functions**

In [ ]:
arr6 = np.random.rand(2,4) # creates randomly generated matrix (0~1) with shape of (2,4)
arr6

array([[0.57111645, 0.57037506, 0.98443385, 0.37198829],
       [0.03335809, 0.201891  , 0.59531077, 0.57140452]])

In [ ]:
arr7 = np.random.randint(90,100, size=(2,4)) # randomly creates from 90 (low), to 100 (highest) and size
arr7

array([[97, 98, 98, 97],
       [95, 95, 94, 95]])

In [ ]:
arr8 = np.random.randn(2, 4) # (2, 4) shape --> elements (Normal dist)
arr8

array([[ 0.20985368,  2.51608112,  1.01408701,  0.44316511],
       [ 0.3466311 ,  3.23145714,  1.02229944, -0.31039895]])

In [ ]:
arr9 = np.random.randint(1000, size=(0,1))
arr9.ndim

2

**Dtype and astype**

In [ ]:
arr_a = np.array([1,2,3], dtype= np.int8)
arr_a

array([1, 2, 3], dtype=int8)

In [ ]:
arr_b = np.array([1,2,3], dtype=np.float64)
arr_b

array([1., 2., 3.])

In [ ]:
arr_a.dtype

dtype('int8')

In [ ]:
float_arr_a = arr_a.astype(np.float64)
float_arr_a

array([1., 2., 3.])

When turning from float to integer pay attention to data loss

In [ ]:
arr_c = np.array([3.3, 2.4, 5.7]) # float 64
int_arr_c = arr_c.astype(np.int64)
int_arr_c

array([3, 2, 5])

**COPY**

In [ ]:
arr_d = np.arange(10,100,10)
arr_d

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#sliced_arr = arr_d[3:5]
#sliced_arr[:] = 0
#print(sliced_arr)
#print(arr_d)   without copy it affects array itself

[0 0]
[10 20 30  0  0 60 70 80 90]


In [ ]:
sliced_arr1 = arr_d[3:5].copy()
sliced_arr1[:] = 0
print(sliced_arr1)
print(arr_d)

[0 0]
[10 20 30 40 50 60 70 80 90]


**Boolen** **Index**

In [ ]:
names = np.array(['Mirsaid', 'Asadbek', 'Doston', 'Mironshoh', 'Mirsaid'])
names

array(['Mirsaid', 'Asadbek', 'Doston', 'Mironshoh', 'Mirsaid'],
      dtype='<U9')

In [ ]:
data = np.random.randn(5,4)
data

array([[-1.12194282,  0.55148122,  1.18411182,  0.14650111],
       [ 1.43195945,  0.11360089, -1.36336536,  0.19629991],
       [-0.43716653, -1.75460412, -0.25372006, -1.68197361],
       [ 1.78695491,  0.3549771 ,  0.55251987, -1.3111975 ],
       [ 0.67016905,  0.85835775,  0.95973051, -0.42357333]])

In [ ]:
names == 'Mirsaid'

array([ True, False, False, False,  True])

In [ ]:
data[names == 'Mirsaid']

array([[-1.12194282,  0.55148122,  1.18411182,  0.14650111],
       [ 0.67016905,  0.85835775,  0.95973051, -0.42357333]])

In [ ]:
data[names == 'Mirsaid', 2:]
# last 2 infos about Mirsaid

array([[ 1.18411182,  0.14650111],
       [ 0.95973051, -0.42357333]])

In [ ]:
data[names != 'Mirsaid']

array([[ 1.43195945,  0.11360089, -1.36336536,  0.19629991],
       [-0.43716653, -1.75460412, -0.25372006, -1.68197361],
       [ 1.78695491,  0.3549771 ,  0.55251987, -1.3111975 ]])

In [ ]:
data[~(names == 'Mirsaid')] # ~ is !=

array([[ 1.43195945,  0.11360089, -1.36336536,  0.19629991],
       [-0.43716653, -1.75460412, -0.25372006, -1.68197361],
       [ 1.78695491,  0.3549771 ,  0.55251987, -1.3111975 ]])

In [ ]:
mask = (names == 'Mirsaid') | (names == 'Mironshoh') # | is or
mask

array([ True, False, False,  True,  True])

In [ ]:
data[mask]

array([[-1.12194282,  0.55148122,  1.18411182,  0.14650111],
       [ 1.78695491,  0.3549771 ,  0.55251987, -1.3111975 ],
       [ 0.67016905,  0.85835775,  0.95973051, -0.42357333]])

In [ ]:
data[data<0] = 0 # elements that is small than 0
data

array([[0.        , 0.55148122, 1.18411182, 0.14650111],
       [1.43195945, 0.11360089, 0.        , 0.19629991],
       [0.        , 0.        , 0.        , 0.        ],
       [1.78695491, 0.3549771 , 0.55251987, 0.        ],
       [0.67016905, 0.85835775, 0.95973051, 0.        ]])

In [3]:
arr = np.random.randint(0,9, size=(3,3))
arr

array([[2, 2, 5],
       [6, 7, 4],
       [6, 0, 0]])

**Reshape, Transpose, Swapping Axes**

In [4]:
A = np.arange(6).reshape(3,2)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
A.T # transposed max: 2d

array([[0, 2, 4],
       [1, 3, 5]])

In [10]:
A.swapaxes(1,0) # used any deminsional arrays

array([[0, 2, 4],
       [1, 3, 5]])

In [11]:
np.dot(A,A.T) # multiplication

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])