In [1]:
import numpy as np

In [3]:
a = np.arange(1,7) # from 1 to 7
print(a)

b = a.reshape((2,3))
print(b)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [5]:
print(a)
print(a.shape)
b = a[:, np.newaxis]
print(b.shape)


[1 2 3 4 5 6]
(6,)
(1, 6)


#Concatenation